// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_likes.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPostLike = `-- name: CreatePostLike :one
INSERT INTO post_likes(user_id, post_id, created_at)
VALUES($1, $2, $3)
RETURNING user_id, post_id, created_at
`

type CreatePostLikeParams struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) (PostLike, error) {
	row := q.db.QueryRowContext(ctx, createPostLike, arg.UserID, arg.PostID, arg.CreatedAt)
	var i PostLike
	err := row.Scan(&i.UserID, &i.PostID, &i.CreatedAt)
	return i, err
}

const deletePostLike = `-- name: DeletePostLike :exec
DELETE FROM post_likes WHERE user_id = $1 AND post_id = $2
`

type DeletePostLikeParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error {
	_, err := q.db.ExecContext(ctx, deletePostLike, arg.UserID, arg.PostID)
	return err
}

const getLikedPostsForUser = `-- name: GetLikedPostsForUser :many
SELECT posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id, feeds.name as feed_name FROM posts
JOIN post_likes ON posts.id = post_likes.post_id
JOIN feeds ON posts.feed_id = feeds.id
WHERE post_likes.user_id = $1
ORDER BY post_likes.created_at DESC
LIMIT $2 OFFSET $3
`

type GetLikedPostsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type GetLikedPostsForUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      uuid.UUID
	FeedName    string
}

func (q *Queries) GetLikedPostsForUser(ctx context.Context, arg GetLikedPostsForUserParams) ([]GetLikedPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getLikedPostsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLikedPostsForUserRow
	for rows.Next() {
		var i GetLikedPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
